// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MoviesApi.Common.Model.ReverseEngineering
{
    [Keyless]
    [Table("people", Schema = "moviesfile")]
    public partial class Person
    {
        [Column("id")]
        public int? Id { get; set; }
        [Column("name", TypeName = "text")]
        public string Name { get; set; }
        [Column("birth")]
        public long? Birth { get; set; }
    }
}