// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MoviesApi.Core.Model.ReverseEngineering
{
    [Keyless]
    [Table("directors", Schema = "moviesfile")]
    public partial class Director
    {
        [Column("movie_id")]
        public int? MovieId { get; set; }
        [Column("person_id")]
        public int? PersonId { get; set; }
    }
}