// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MoviesApi.Core.Model.ReverseEngineering
{
    [Keyless]
    [Table("movies", Schema = "moviesfile")]
    public partial class Movie
    {
        [Column("id")]
        public int? Id { get; set; }
        [Column("title", TypeName = "text")]
        public string Title { get; set; }
        [Column("year")]
        public long? Year { get; set; }
    }
}