// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace MoviesApi.Core.Model.ReverseEngineering
{
    [Keyless]
    [Table("ratings", Schema = "moviesfile")]
    public partial class Rating
    {
        [Column("movie_id")]
        public int? MovieId { get; set; }
        [Column("rating")]
        public float? Rating1 { get; set; }
        [Column("votes")]
        public int? Votes { get; set; }
    }
}