// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MoviesApi.Core.Interfaces;

#nullable disable

namespace MoviesApi.Core.Model
{
    [Keyless]
    [Table("movies", Schema = "moviesfile")]
    public partial class Movie :ISearchable
    {
        [Column("id")]
        private int id { get; set; }
        [NotMapped]
        public string Id { get => "tt" + id; set { id = int.Parse(value); } }
        [Column("title", TypeName = "text")]
        public string Title { get; set; }
        [Column("year")]
        public long? Year { get; set; }
        [Column("search_string")]
        public string SearchString { get; set; }
    }
}